# Nombre del pipeline
name: Integracion Continua

#pasos para ejecutar pipeline
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar el JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Ejecutar pruebas
        run: ./gradlew test --no-daemon

on:
  push:
    branches:
      - main
